### ISSUE TITLE
[REQUEST] Termage as a standalone app?

### ISSUE THREAD

**Issue by kseistrup** [bczsalba/mkdocs-termage-plugin#3]
**Is your feature request related to a problem? Please describe.**

Could `termage` be implented as a standalone app?

**Describe the solution you'd like**

It would be weet to be able to generate an SVG (or more generally, an image) from a given code file. E.g.:

```sh
$ termage --help
Usage: termage [INPUT [OUTPUT]]
$ termage hello-world.py hello-world.svg
```

**Describe alternatives you've considered**

I usually go to https://carbon.now.sh/ to generate images from my code, so that I can post it on e.g. social media or on a blog. It would be sweeter to be able to do it from the commandline.

**Comment by bczsalba** [comment]
I was thinking about doing this earlier today. Most of the SVG functionality is just wrapped from what PTG is doing, though Termage is probably a "cleaner" place to put things like syntax-highlighted SVG exports.


For the record, you can do `cat hello-world.py | ptg --highlight --export-svg "hello-world.svg"` already, but it's a tad wordy and not very intuitive.

**Comment by kseistrup** [comment]
Thanks, mate!

**Comment by bczsalba** [comment]
[Working](https://twitter.com/BcZsalba/status/1529836783399215105?s=20&t=GKVL_QTXQBheRYoGg6Zw8w) on it! :)

**Comment by bczsalba** [comment]
Out now! Thanks for the suggestion!

**Comment by kseistrup** [comment]
Fantastic! :pray:
