### ISSUE TITLE
[BUG] Cannot install with pip: No module named ‘mkdocs_termage_plugin’

### ISSUE THREAD

**Issue by kseistrup** [bczsalba/mkdocs-termage-plugin#4]
**Describe the bug**

When calling `pip install mkdocs-termage-plugin` the installation fails, seemingly because of a `ModuleNotFoundError`.

**To Reproduce**

Just run `pip install mkdocs-termage-plugin` from a terminal prompt.

**Expected behavior**

I expected the package to be downloaded and installed.

**Screenshots**

![pip-install-fail-ck9nhfdsur68](https://user-images.githubusercontent.com/25586/170478013-1a7f4c25-9106-4c00-8348-5002ea3bf704.png)

**Platform info**
Browser: Not a browser, see screenshot of terminal

**Comment by bczsalba** [comment]
This is super weird, PyTermGUI uses the same pattern with no issues, but it fails here. Seems fixed on my machine now.

Thank you for the report!

**Comment by bczsalba** [comment]
Nevermind, something is wrong again 😆

**Comment by kseistrup** [comment]
Oh? Version 0.1.1 from PyPI seemed to install without problems… :thinking:

**Comment by bczsalba** [comment]
Something was wrong with my environment, but it seems to work fine now. Oh the wonders of packaging!
